version: '3.8'

services:
  jekyll_website:
    image: my-jekyll-site
    container_name: jekyll_website
    volumes:
      - ".:/srv/jekyll"
    ports:
      - "4000:4000"
    restart: always
    
networks:
  default:
    name: shared-network  
    external: true

# Create a network with the name shared-network : docker network create shared-network
