FROM ruby:3.0

RUN apt-get update && \
    apt-get install -y build-essential && \
    gem install jekyll bundler

RUN bundle install

RUN addgroup --system jekyll_group && adduser --system jekyll_user --ingroup jekyll_group
USER jekyll_user

WORKDIR /srv/jekyll

CMD ["bundle", "exec", "jekyll", "serve", "--watch", "--force_polling", "--host", "0.0.0.0"]

