name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: debian-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: SSH key setup
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy site
      run: 
        ssh -o StrictHostKeyChecking=no -p 1068 guillaume@guillaume-rohee.me "cd /srv/knowledge-base && docker-compose up -d"
