name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install SSH
      run: sudo apt-get install -y sshpass

    - name: Rebuild the website on the server
      run: eval "$(ssh-agent -s)" && ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"; ssh -o StrictHostKeyChecking=no -p 1068 github-actions@guillaume-rohee.me "cd /home/guillaume/srv/knowledge-base && git pull && docker-compose up -d"
