name: Deploy to VPS

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true  
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install SSH
      run: sudo apt-get install -y sshpass

    - name: Rebuild the website on the server
      run: eval "$(ssh-agent -s)" && ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"; ssh -o StrictHostKeyChecking=no -p 1068 github-actions@guillaume-rohee.fr "cd /home/guillaume/srv/knowledge-base && git pull && docker-compose up -d"
